### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Neo19867** [Cybertat1on/GoblinMine#1]
i have strange errors today 
![image](https://github.com/user-attachments/assets/ad37a53c-e848-4836-88cb-39607fdf8562)

**Comment by kykypyza13** [comment]
same
![image](https://github.com/user-attachments/assets/0ca257cd-c4de-46d6-a52a-00156a6650e5)

**Comment by RMOmd** [comment]
same problem:

```
2024-11-08 11:30:06 | ERROR    | 179  | goblin_mine_md | Unknown error
Traceback (most recent call last):

  File "D:\soft\memefi\GoblinMine-main_1\main.py", line 13, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x000001E809C98A40>
    │       └ <function run at 0x000001E80BC4C2C0>
    └ <module 'asyncio' from 'C:\\Users\\*********\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x000001E80F520040>
           │      └ <function Runner.run at 0x000001E80BCC3F60>
           └ <asyncio.runners.Runner object at 0x000001E80F4E6060>
  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at D:\soft\memefi\GoblinMine-main_1\main.py:8> wait_for=<_GatheringFuture pe...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001E80BCC1B20>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001E80F4E6060>
  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001E80BD99D00>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001E80BCC3880>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1971, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001E80BC0D580>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\*********\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "D:\soft\memefi\GoblinMine-main_1\bot\launcher.py", line 98, in run_bot_with_delay
    await run_bot(tg_client=tg_client, proxy=proxy, additional_data=additional_data)
          │                 │                │                      └ [{'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 17_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0.1 Mobi...
          │                 │                └ None
          │                 └ <pyrogram.client.Client object at 0x000001E80F53B3E0>
          └ <function run_bot at 0x000001E80F0A7880>

  File "D:\soft\memefi\GoblinMine-main_1\bot\core\bot.py", line 195, in run_bot
    await CryptoBot(tg_client=tg_client, additional_data=additional_data).run(proxy=proxy)
          │                   │                          │                          └ None
          │                   │                          └ [{'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 17_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0.1 Mobi...
          │                   └ <pyrogram.client.Client object at 0x000001E80F53B3E0>
          └ <class 'bot.core.bot.CryptoBot'>

> File "D:\soft\memefi\GoblinMine-main_1\bot\core\bot.py", line 159, in run
    await self.rotate_spin()
          │    └ <function CryptoBotApi.rotate_spin at 0x000001E80F5322A0>
          └ <bot.core.bot.CryptoBot object at 0x000001E80F6EE390>

  File "D:\soft\memefi\GoblinMine-main_1\bot\helper\decorators.py", line 17, in wrapper
    return await func(*args, **kwargs)
                 │     │       └ {}
                 │     └ (<bot.core.bot.CryptoBot object at 0x000001E80F6EE390>,)
                 └ <function CryptoBotApi.rotate_spin at 0x000001E80F5323E0>

  File "D:\soft\memefi\GoblinMine-main_1\bot\helper\decorators.py", line 58, in wrapper
    return await func(self, response_json=response_data, **kwargs)
                 │    │                   │                └ {}
                 │    │                   └ {'errors': [{'message': 'Variable "$input" of required type "BuyMineInput!" was not provided.', 'locations': [{'line': 1, 'co...
                 │    └ <bot.core.bot.CryptoBot object at 0x000001E80F6EE390>
                 └ <function CryptoBotApi.rotate_spin at 0x000001E80F532340>

  File "D:\soft\memefi\GoblinMine-main_1\bot\core\api.py", line 45, in rotate_spin
    return response_json["data"]
           └ {'errors': [{'message': 'Variable "$input" of required type "BuyMineInput!" was not provided.', 'locations': [{'line': 1, 'co...

KeyError: 'data'
2024-11-08 11:30:52 | ERROR    | 137  | goblin_mine_md | Bot stopped (too many errors)
```

**Comment by RMOmd** [comment]
==================================================

************************** S O L U T I O N **************************************

Disable ROTATE_SPIN: bool =  from TRUE to False in \bot\config\settings.py

*********************************************************************************

**Comment by kirajok** [comment]
> ==================================================
> 
> ************************** S O L U T I O N **************************************
> 
> Disable ROTATE_SPIN: bool = from TRUE to False in \bot\config\settings.py

Same problem but your solution is work, thanks

**Comment by RMOmd** [comment]
> > ==================================================
> > ************************** S O L U T I O N **************************************
> > Disable ROTATE_SPIN: bool = from TRUE to False in \bot\config\settings.py
> 
> Same problem but your solution is work, thanks

solution work, but not very long time. Problem not fully solved

**Comment by nikitas244** [comment]
`2024-11-12 11:02:39 | INFO     | 190  | nikitasik | Claimed 4.6
2024-11-12 11:02:41 | INFO     | 190  | nikitasik | Claimed 160.1
2024-11-12 11:02:44 | INFO     | 190  | nikitasik | Claimed 171.3
2024-11-12 11:02:46 | INFO     | 190  | nikitasik | Claimed 297.4
2024-11-12 11:02:49 | INFO     | 190  | nikitasik | Claimed 671.3
2024-11-12 11:02:52 | INFO     | 190  | nikitasik | Claimed 960.7
2024-11-12 11:02:54 | SUCCESS  | 43   | nikitasik | ??                                              1 ???
2024-11-12 11:02:55 | SUCCESS  | 68   | nikitasik | ?? Start of auto-upgrade INVENTORY for mine       1 ???
2024-11-12 11:02:57 | INFO     | 79   | nikitasik | ?? Completed auto-upgrade INVENTORY for mine       1 ?
2024-11-12 11:02:57 | SUCCESS  | 82   | nikitasik | ?? Start of auto-upgrade MINE for mine       1 ???
2024-11-12 11:02:58 | INFO     | 92   | nikitasik | ?? Completed auto-upgrade MINE for mine       1 ?
2024-11-12 11:02:58 | SUCCESS  | 95   | nikitasik | ?? Start of auto-upgrade MINE for mine       1 ???
2024-11-12 11:02:58 | INFO     | 115  | nikitasik | ?? Completed auto-upgrade  MINERS for mine       1 ?
2024-11-12 11:02:59 | SUCCESS  | 43   | nikitasik | ??                                              2 ???
2024-11-12 11:03:00 | SUCCESS  | 68   | nikitasik | ?? Start of auto-upgrade INVENTORY for mine       2 ???
2024-11-12 11:03:01 | INFO     | 79   | nikitasik | ?? Completed auto-upgrade INVENTORY for mine       2 ?
2024-11-12 11:03:01 | SUCCESS  | 82   | nikitasik | ?? Start of auto-upgrade MINE for mine       2 ???
2024-11-12 11:03:02 | INFO     | 92   | nikitasik | ?? Completed auto-upgrade MINE for mine       2 ?
2024-11-12 11:03:02 | SUCCESS  | 95   | nikitasik | ?? Start of auto-upgrade MINE for mine       2 ???
2024-11-12 11:03:02 | INFO     | 115  | nikitasik | ?? Completed auto-upgrade  MINERS for mine       2 ?
2024-11-12 11:03:04 | SUCCESS  | 43   | nikitasik | ??                                              3 ???
2024-11-12 11:03:06 | SUCCESS  | 68   | nikitasik | ?? Start of auto-upgrade INVENTORY for mine       3 ???
2024-11-12 11:03:07 | INFO     | 79   | nikitasik | ?? Completed auto-upgrade INVENTORY for mine       3 ?
2024-11-12 11:03:07 | SUCCESS  | 82   | nikitasik | ?? Start of auto-upgrade MINE for mine       3 ???
2024-11-12 11:03:08 | INFO     | 92   | nikitasik | ?? Completed auto-upgrade MINE for mine       3 ?
2024-11-12 11:03:08 | SUCCESS  | 95   | nikitasik | ?? Start of auto-upgrade MINE for mine       3 ???
2024-11-12 11:03:09 | INFO     | 115  | nikitasik | ?? Completed auto-upgrade  MINERS for mine       3 ?
2024-11-12 11:03:10 | SUCCESS  | 43   | nikitasik | ??                                              4 ???
2024-11-12 11:03:11 | SUCCESS  | 68   | nikitasik | ?? Start of auto-upgrade INVENTORY for mine       4 ???
2024-11-12 11:03:13 | INFO     | 79   | nikitasik | ?? Completed auto-upgrade INVENTORY for mine       4 ?
2024-11-12 11:03:13 | SUCCESS  | 82   | nikitasik | ?? Start of auto-upgrade MINE for mine       4 ???
2024-11-12 11:03:15 | INFO     | 92   | nikitasik | ?? Completed auto-upgrade MINE for mine       4 ?
2024-11-12 11:03:15 | SUCCESS  | 95   | nikitasik | ?? Start of auto-upgrade MINE for mine       4 ???
2024-11-12 11:03:15 | INFO     | 115  | nikitasik | ?? Completed auto-upgrade  MINERS for mine       4 ?
2024-11-12 11:03:16 | SUCCESS  | 43   | nikitasik | ??                                              5 ???
2024-11-12 11:03:17 | SUCCESS  | 68   | nikitasik | ?? Start of auto-upgrade INVENTORY for mine       5 ???
2024-11-12 11:03:19 | INFO     | 79   | nikitasik | ?? Completed auto-upgrade INVENTORY for mine       5 ?
2024-11-12 11:03:19 | SUCCESS  | 82   | nikitasik | ?? Start of auto-upgrade MINE for mine       5 ???
2024-11-12 11:03:20 | INFO     | 92   | nikitasik | ?? Completed auto-upgrade MINE for mine       5 ?
2024-11-12 11:03:20 | SUCCESS  | 95   | nikitasik | ?? Start of auto-upgrade MINE for mine       5 ???
2024-11-12 11:03:20 | INFO     | 115  | nikitasik | ?? Completed auto-upgrade  MINERS for mine       5 ?
2024-11-12 11:03:21 | SUCCESS  | 43   | nikitasik | ??                                              6 ???
2024-11-12 11:03:22 | SUCCESS  | 68   | nikitasik | ?? Start of auto-upgrade INVENTORY for mine       6 ???
2024-11-12 11:03:25 | INFO     | 76   | nikitasik | ? Successfully upgraded                 to level 2 ?? cost -310.0k for mine       6 ?
2024-11-12 11:03:25 | INFO     | 79   | nikitasik | ?? Completed auto-upgrade INVENTORY for mine       6 ?
2024-11-12 11:03:25 | SUCCESS  | 82   | nikitasik | ?? Start of auto-upgrade MINE for mine       6 ???
2024-11-12 11:03:27 | INFO     | 92   | nikitasik | ?? Completed auto-upgrade MINE for mine       6 ?
2024-11-12 11:03:27 | SUCCESS  | 95   | nikitasik | ?? Start of auto-upgrade MINE for mine       6 ???
2024-11-12 11:03:27 | INFO     | 115  | nikitasik | ?? Completed auto-upgrade  MINERS for mine       6 ?
2024-11-12 11:03:41 | ERROR    | 179  | nikitasik | Unknown error
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\GoblinMine-main\main.py", line 13, in <module>
    asyncio.run(main())
                L <function main at 0x0000022964CB3E20>
            L <function run at 0x00000229651643A0>
    L <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
                                   L <coroutine object main at 0x000002296AAFD930>
                L <function BaseEventLoop.run_until_complete at 0x0000022967173370>
           L <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
         L <function ProactorEventLoop.run_forever at 0x000002296721FA30>
    L <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
         L <function BaseEventLoop._run_once at 0x0000022967174E50>
    L <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
           L <function Handle._run at 0x00000229670CBAC0>
    L <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
                                            L <member '_args' of 'Handle' objects>
                                       L <Handle Task.task_wakeup(<Future finished result=None>)>
                           L <member '_callback' of 'Handle' objects>
                      L <Handle Task.task_wakeup(<Future finished result=None>)>
         L <member '_context' of 'Handle' objects>
    L <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\launcher.py", line 98, in run_bot_with_delay
    await run_bot(tg_client=tg_client, proxy=proxy, additional_data=additional_data)
                                                                    L [{'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/1...
                                             L None
                            L <pyrogram.client.Client object at 0x000002296AB39C30>
          L <function run_bot at 0x000002296A690C10>

  File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\core\bot.py", line 195, in run_bot
    await CryptoBot(tg_client=tg_client, additional_data=additional_data).run(proxy=proxy)
                                                                                    L None
                                                         L [{'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/1...
                              L <pyrogram.client.Client object at 0x000002296AB39C30>
          L <class 'bot.core.bot.CryptoBot'>

> File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\core\bot.py", line 169, in run
    await self.perform_expeditions()
               L <function CryptoBot.perform_expeditions at 0x000002296AB2DEA0>
          L <bot.core.bot.CryptoBot object at 0x000002296ADB0490>

  File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\core\bot.py", line 61, in perform_expeditions
    await self.send_expedition(json_body={"id": i.id})
                                                  L 4943394
                                                L UserExpeditions(amount=7000000, created_at=datetime.datetime(2024, 11, 8, 4, 10, 22), status='is_done', name='global Expediti...
               L <function CryptoBotApi.send_expedition at 0x000002296AB2D3F0>
          L <bot.core.bot.CryptoBot object at 0x000002296ADB0490>

  File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\helper\decorators.py", line 17, in wrapper
    return await func(*args, **kwargs)
                               L {'json_body': {'id': 4943394}}
                       L (<bot.core.bot.CryptoBot object at 0x000002296ADB0490>,)
                 L <function CryptoBotApi.send_expedition at 0x000002296AB2D510>

  File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\helper\decorators.py", line 58, in wrapper
    return await func(self, response_json=response_data, **kwargs)
                                                           L {'json_body': {'id': 4943394}}
                                          L {'errors': [{'message': 'Variable "$Id" of required type "Int!" was not provided.', 'locations': [{'line': 1, 'column': 18}]}]}
                      L <bot.core.bot.CryptoBot object at 0x000002296ADB0490>
                 L <function CryptoBotApi.send_expedition at 0x000002296AB2D480>

  File "C:\Users\Administrator\Desktop\GoblinMine-main\bot\core\api.py", line 100, in send_expedition
    return response_json["data"]
           L {'errors': [{'message': 'Variable "$Id" of required type "Int!" was not provided.', 'locations': [{'line': 1, 'column': 18}]}]}

KeyError: 'data'
`

**Comment by nikitas244** [comment]
Делал как сверху, но всё равно данная ошибка вылезает.

**Comment by GoldVital** [comment]
Отключил как советовали выше ROTATE_SPIN: bool + отключил в файле .env -  SEND_EXPEDITION
Идет пока без ошибки

**Comment by RMOmd** [comment]
я еще к этому сделал порог ошибок выше, ошибки сыпятся, но бот не выключается. Повышал лимит тут:  \bot\config\settings.py ERRORS_BEFORE_STOP: int = 9999

**Comment by nikitas244** [comment]
> Отключил как советовали выше ROTATE_SPIN: bool + отключил в файле .env - SEND_EXPEDITION Идет пока без ошибки

кстати, да, тоже помогло, но на VDS через .bat бывает вообще бот замерзает

**Comment by GoldVital** [comment]
Все наигрался, бан, хотя с телефона заходит ))

![image](https://github.com/user-attachments/assets/22d09957-20c2-4165-a60e-900cc2b4b231)

![image](https://github.com/user-attachments/assets/d85ae960-e5e4-4cec-aa8e-44842ea2a631)

**Comment by nikitas244** [comment]
Ну да, интересно, тоже самая ошибка, но с мобилки захожу. 😳

**Comment by nikitas244** [comment]
> Все наигрался, бан, хотя с телефона заходит ))
> 
> ![image](https://private-user-images.githubusercontent.com/179118006/386874017-22d09957-20c2-4165-a60e-900cc2b4b231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDczNTEsIm5iZiI6MTczMTg0NzA1MSwicGF0aCI6Ii8xNzkxMTgwMDYvMzg2ODc0MDE3LTIyZDA5OTU3LTIwYzItNDE2NS1hNjBlLTkwMGNjMmI0YjIzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMjM3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTRkNmNmNzQ5ZDNhMGFjZGVjZTdkOTYwYmE5OGMzOTBkNDBiYzIxYjVjNjEyZTg1OGRhODJjNjAyNTA4MjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mhx8a2zIoyD_17-mY1WHj_GTnyvI4cDJa0uF-v0aNy4)
> 
> ![image](https://private-user-images.githubusercontent.com/179118006/386873981-d85ae960-e5e4-4cec-aa8e-44842ea2a631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDczNTEsIm5iZiI6MTczMTg0NzA1MSwicGF0aCI6Ii8xNzkxMTgwMDYvMzg2ODczOTgxLWQ4NWFlOTYwLWU1ZTQtNGNlYy1hYThlLTQ0ODQyZWEyYTYzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMjM3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTAyZTdhOWU4Yjk3OTM3ZGYyODM1Njc2ODk1MmMwNzA5NmIwODJjMzhiODY2ZDE1ZWEyMjE4NWU2ZjE2YWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ihP1lwoQjPUV2POmnTnMbJUD-UldE4wrruvRet7s29w)

скорее всего это не бан аккаунта, а что-то в API изменили.
